import Head from 'next/head'
import Image from 'next/image'
import CountUp from 'react-countup'
import VisibilitySensor from 'react-visibility-sensor'
import Nav from '../pages/'
import Main from '../pages/Main'
import Footer from '../pages/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aspire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Main />
      <Footer />
    </>
  )
}
